service: notes-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    MONGODB_URI: ${param:mongodb_uri}

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:

  boardCreate:
    handler: bin/board/create
    events:
      - httpApi:
          path: /board/new
          method: post

  boardGet:
    handler: bin/board/get
    events:
      - httpApi:
          path: /board/{id}
          method: get

  boardGetAll:
    handler: bin/board/get_all
    events:
      - httpApi:
          path: /boards
          method: get

  boardUpdate:
    handler: bin/board/update
    events:
      - httpApi:
          path: /board/{id}
          method: put

  boardDelete:
    handler: bin/board/delete
    events:
      - httpApi:
          path: /board/{id}
          method: delete

  noteCreate:
    handler: bin/note/create
    events:
      - httpApi:
          path: /board/{boardID}/note/new
          method: post

  noteGet:
    handler: bin/note/get
    events:
      - httpApi:
          path: /board/{boardID}/note/{noteID}
          method: get

  noteGetAll:
    handler: bin/note/get_all
    events:
      - httpApi:
          path: /board/{boardID}/notes
          method: get

  noteUpdate:
    handler: bin/note/update
    events:
      - httpApi:
          path: /board/{boardID}/note/{noteID}
          method: put

  noteDelete:
    handler: bin/note/delete
    events:
      - httpApi:
          path: /board/{boardID}/note/{noteID}
          method: delete
