service: notes-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    BOARDS_TABLE: BoardsTable
    NOTES_TABLE: NotesTable

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BOARDS_TABLE}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.NOTES_TABLE}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:

  boardCreate:
    handler: bin/board/create
    events:
      - httpApi:
          path: /board/new
          method: post

  boardGet:
    handler: bin/board/get
    events:
      - httpApi:
          path: /board/{id}
          method: get

  boardGetAll:
    handler: bin/board/get_all
    events:
      - httpApi:
          path: /boards
          method: get

  boardUpdate:
    handler: bin/board/update
    events:
      - httpApi:
          path: /board/{id}
          method: put

  boardDelete:
    handler: bin/board/delete
    events:
      - httpApi:
          path: /board/{id}
          method: delete

  noteCreate:
    handler: bin/note/create
    events:
      - httpApi:
          path: /board/{boardID}/note/new
          method: post

  noteGet:
    handler: bin/note/get
    events:
      - httpApi:
          path: /board/{boardID}/note/{noteID}
          method: get

  noteGetAll:
    handler: bin/note/get_all
    events:
      - httpApi:
          path: /board/{boardID}/notes
          method: get

  noteUpdate:
    handler: bin/note/update
    events:
      - httpApi:
          path: /board/{boardID}/note/{noteID}
          method: put

  noteDelete:
    handler: bin/note/delete
    events:
      - httpApi:
          path: /board/{boardID}/note/{noteID}
          method: delete

resources:
  Resources:
    BoardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.BOARDS_TABLE}
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: board_id
          AttributeType: S
        - AttributeName: note_id
          AttributeType: S
        KeySchema:
        - AttributeName: board_id
          KeyType: HASH
        - AttributeName: note_id
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.NOTES_TABLE}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
